---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secrets
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: qbittorrent-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENVPN_USER: '{{ .QBT_OPENVPN_USER }}'
        OPENVPN_PASSWORD: '{{ .QBT_OPENVPN_PASSWORD }}'
        custom.ovpn: '{{ .QBT_OPENVPN_CUSTOM_CONFIG }}'

  dataFrom:
    - find:
        path: QBT_
