---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mosquitto
spec:
  chartRef:
    kind: OCIRepository
    name: mosquitto
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
              pullPolicy: IfNotPresent
            command: [ "/bin/sh", "-c" ]
            args: [ "cp /tmp/secret/* /mosquitto/external_config/ && chmod 0700 /mosquitto/external_config/mosquitto_pwd && mosquitto_passwd -U /mosquitto/external_config/mosquitto_pwd" ]
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.22
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              limits: &resources
                memory: 128Mi
              requests:
                <<: *resources
                cpu: 10m
        pod:
          securityContext:
            runAsUser: 1883
            runAsGroup: 1883
            runAsNonRoot: true
            fsGroup: 1883
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_MOSQUITTO_ADDR}
        ports:
          http:
            port: 1883

    persistence:
      config:
        existingClaim: mosquitto
        globalMounts:
          - path: /data

      config-file:
        type: configMap
        name: mosquitto-configmap
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
            readOnly: true

      secret-file:
        type: secret
        name: mosquitto-secret
        advancedMounts:
          mosquitto:
            init-config:
              - path: /tmp/secret

      external-config:
        type: emptyDir
        globalMounts:
          - path: /mosquitto/external_config
