---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./serviceaccount.yaml
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/name: garmin-ci-dind
      app.kubernetes.io/instance: garmin-ci-dind
