---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ca
  namespace: network
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDfTCCAmWgAwIBAgIEapKaIzANBgkqhkiG9w0BAQsFADBrMQswCQYDVQQGEwJV
    UzERMA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMRYwFAYDVQQK
    DA1VYmlxdWl0aSBJbmMuMQ4wDAYDVQQLDAVVbmlGaTEOMAwGA1UEAwwFVW5pRmkw
    HhcNMjYwODI5MDgzNjUxWhcNMjgxMjAxMDgzNjUxWjBrMQswCQYDVQQGEwJVUzER
    MA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMRYwFAYDVQQKDA1V
    YmlxdWl0aSBJbmMuMQ4wDAYDVQQLDAVVbmlGaTEOMAwGA1UEAwwFVW5pRmkwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDap43ljepnx3Ylc0Pc47i7/7Ob
    Z2KlyzdCMjg37KQpEizOWL2u2oBHXs+k6gZFxJ/qQg/K5OIXShkPAdRhWWxVXIqQ
    KCFeoJK0amdvVb455GRgSVXmUUDc0kpweBXE35DRNCtCyHm3IzIu8PeKhoG7z0Kg
    BbxJ5eQ/OU+MzNADrQYEZBw4sbDB/SbhZKYnZEmliqvqlUsaqYy34D9nrnrLL+yX
    Y4hlyx+N3Asv2ZfM1cEfcGmPm12gcqmB3x5+A+PL6sBBTkS/I8Sc59nurteaBDUS
    Qn425PRYE2qswOujfZiAafeyBAM69JcaT4Ktqwn+TtsCCpCoPSIGreILgVRlAgMB
    AAGjKTAnMBAGA1UdEQQJMAeCBVVuaUZpMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA0G
    CSqGSIb3DQEBCwUAA4IBAQDKFWuv/8Idy9Q8//WUeW3wZi66vhlQMqY+Q5IZEpzk
    bQjUIR2z/CA6OkOHWF1Ud7maQ2nL2FgZ/jk9YQhiv5g2Ak2HDgVcWl7bjyRwnjXv
    bFstbOMxcuGrBwqNztoDia8hlGg3kdNQKHlvOFxq0TSvG1DGw8rLlTMiZLmJwzr2
    LM4hoQBoFO37v0O2kA/L2r5rYCeJOcSUjtxilxX94ksghETdkGDTRe6ffuOKYY/h
    OkJUMKytSvlWR5MTIoH6nG56hlRsLWqisf8IN2JD13OU9i4iCO4LGZGvle6kgxH7
    fTXi73fH7z83+xvyG6VVBuNPinJUlmuofvnqfUWsty5D
    -----END CERTIFICATE-----
